(TeX-add-style-hook "books"
 (function
  (lambda ()
    (LaTeX-add-bibitems
     "sedgewick-algorithms-in-c"
     "understanding-the-new-sql"
     "applied-cryptography"
     "goosens-mittelbach-samarin:the-latex-companion"
     "greenspun:sql-for-web-nerds"
     "a-relational-model-of-data-for-large-shared-databanks"
     "a-guide-to-latex"
     "mez-waco"
     "goedelescherbach"
     "tanenbaumoperatingsystems"
     "knuthliterateprogramming"
     "Dybvig:1996:SPL"
     "phillipandalexsguidetowebpublishing"
     "sewell:weaving-a-program"
     "srinivasan:advanced-perl-programming"
     "wille-koller:teach-yourself-active-server-pages-in-24-hours"
     "vulis:modern-tex-and-its-applications"
     "wilf:algorithms-and-complexity"
     "webmaster-in-a-nutshell"
     "descartes-bunce:programming-the-perl-dbi"
     "christiansen-torkington:perl-cookbook"
     "goosens-rahtz-mittelbach:the-latex-graphics-companion"
     "franquin:vakse-viggo-4"
     "brooks:the-mythical-man-month"
     "goosens-rahtz:the-latex-web-companion"
     "stern-maceachern:writing-apache-modules-with-perl-and-c"
     "roelofs:png-the-definitive-guide"
     "frisch:essential-system-administration"
     "franquin:det-var-kattens-viggo"
     "bedre-blanketter"))))

